version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    versioning-strategy: 'increase'
    allow:
      - dependency-name: '@admiral-ds/admiral3-icons'
      - dependency-name: '@admiral-ds/admiral3-tokens'
