import { INPUT_DIMENSIONS, INPUT_DIMENSION_PARAMETERS } from '../_internal/InputAtoms/constants';

export const CHECK_BOX_DIMENSIONS = INPUT_DIMENSIONS;
export const CHECK_BOX_DIMENSION_PARAMETERS = INPUT_DIMENSION_PARAMETERS;
